version: '2'
services:
    jhipster_microservice-mysql:
        container_name: jhipster_microservice-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/jhipster_microservice/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipster_microservice
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
